app/views/apikeys.py
from flask import Blueprint, redirect, render_template, current_app
from flask import request, url_for, flash, send_from_directory, jsonify, render_template_string
from flask_user import current_user, login_required, roles_accepted

from flask import Flask, session, redirect, url_for, request, render_template, jsonify, abort
from app import db
from app.models import user_models as users
from app.utils import forms

import time
import uuid


# When using a Flask app factory we must use a blueprint to avoid needing 'app' for '@apikeys_blueprint.route'
apikeys_blueprint = Blueprint('apikeys', __name__, template_folder='templates')


@apikeys_blueprint.route('/user/apikeys')
@roles_accepted('dev', 'admin')
def apikeys_index():
    all_keys = users.ApiKey.query.filter_by(user_id=current_user.id).all()
    return render_template("apikeys/list.html", keys=all_keys)


@apikeys_blueprint.route('/user/create_apikey', methods=['GET', 'POST'])
@roles_accepted('dev', 'admin')
def apikeys_create():
    form = users.ApiKeyForm(request.form)
    if request.method == 'POST' and form.validate():
        label = request.form.get('label', None)
        id = uuid.uuid4().hex[0:12]
        key = uuid.uuid4().hex
        hash = current_app.user_manager.hash_password(key)
        new_key = users.ApiKey(id=id, hash=hash, user_id=current_user.id, label=label)
        db.session.add(new_key)
        db.session.commit()
        return render_template("apikeys/newkey.html", id=id, key=key, label=label)
    return render_template("apikeys/create.html", form=form)


@apikeys_blueprint.route('/user/apikeys/<key_id>/delete', methods=['GET', 'POST'])
@roles_accepted('dev', 'admin')
def apikeys_delete(key_id):
    form = forms.ConfirmationForm(request.form)
    if request.method == 'POST':
        remove_key = users.ApiKey.query.filter_by(id=key_id, user_id=current_user.id).first()
        if remove_key:
            db.session.delete(remove_key)
            db.session.commit()
        return redirect(url_for('apikeys.apikeys_index'))
    return render_template("apikeys/delete.html", form=form, key_id=key_id)

app/templates/apikeys/create.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
{% block title %}Create a new API Key{% endblock %}
{% block breadcrumb %}
<li class="breadcrumb-item active">
  <a href="{{ url_for('apikeys.apikeys_index') }}">API Keys</a>
</li>
{% endblock %}
{% block content %}
{% from "common/form_macros.html" import render_field %}
<div class="card ">
  <form action="" method="POST" class="form" role="form">
    <div class="card-header ">
      <strong>New Key</strong>
    </div>
    <div class="card-body ">
          {{ form.hidden_tag() }}
          {{ render_field(form.label) }}
    </div>
    <div class="card-footer ">
      <button type="submit " class="btn btn-sm btn-primary "><i class="fa fa-dot-circle-o "></i> Submit</button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/apikeys/delete.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
{% block title %}Delete API Key {{ key_id }}{% endblock %}
{% block breadcrumb %}
<li class="breadcrumb-item active">
  <a href="{{ url_for('apikeys.apikeys_index') }}">API Keys</a>
</li>
{% endblock %}
{% block content %}
{% from "common/form_macros.html" import render_field %}
<div class="card ">
  <form action="" method="POST" class="form" role="form">
    <div class="card-header ">
      <strong>Delete Key {{ key_id }}</strong>
    </div>
    <div class="card-body ">
          {{ form.hidden_tag() }}
    </div>
    <div class="card-footer ">
      <button type="submit " class="btn btn-sm btn-primary "><i class="fa fa-dot-circle-o "></i> Delete</button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/apikeys/list.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
{% block breadcrumb %}
<li class="breadcrumb-item active">
  <a href="{{ url_for('apikeys.apikeys_index') }}">API Keys</a>
</li>
{% endblock %}
{% block content %}
<div class="card ">
    <div class="card-header ">
      <strong>API Keys</strong>
      <a href={{ url_for('apikeys.apikeys_create') }} class="btn btn-pill btn-sm btn-primary pull-right">Create Key</a>
    </div>
    <div class="card-body ">
      <table class="table table-hover table-striped" style="padding-top: 50px;">
        <thead>
          <tr>
            <th>ID</th>
            <th>Label</th>
            <th>Control</th>
          </tr>
        </thead>
        <tbody>
          {% for key in keys %}
          <tr>
            <td>{{ key.id }}</td>
            <td>{{ key.label }}</td>
            <td>
              <div class="btn-group" role="group" aria-label="...">
                <a href="{{ url_for('apikeys.apikeys_delete', key_id=key.id) }}"><i class="fa fa-remove"></i></a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="card-footer ">
    </div>
</div>
{% endblock %}

app/templates/apikeys/newkey.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{{ url_for('apikeys.apikeys_index') }}">API Keys</a>
</li>
{% endblock %}
{% block title %}Your new API Key{% endblock %}
{% block content %}
<div class="card ">
    <div class="card-header ">
      <strong>Your new API Key</strong>
    </div>
    <div class="card-body ">
      <table class="table table-hover table-striped" style="padding-top: 50px;">
        <thead>
          <tr>
            <th>ID</th>
            <th>Key</th>
            <th>Label</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{ id }}</td>
            <td>{{ key }}</td>
            <td>{{ label }}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="card-footer ">
    </div>
</div>
{% endblock %}