app/views/misc_views.py
# Copyright 2017 Twin Tech Labs. All rights reserved

from flask import Blueprint, redirect, render_template, current_app, abort
from flask import request, url_for, flash, send_from_directory, jsonify, render_template_string
from flask_user import current_user, login_required, roles_accepted

from app import db
from app.models.user_models import UserProfileForm, User, UsersRoles, Role
from app.utils.forms import ConfirmationForm
import uuid, json, os
import datetime

# When using a Flask app factory we must use a blueprint to avoid needing 'app' for '@app.route'
main_blueprint = Blueprint('main', __name__, template_folder='templates')

# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route('/')
def member_page():
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    return render_template('pages/member_base.html')

# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route('/admin')
@roles_accepted('admin')
def admin_page():
    return redirect(url_for('main.user_admin_page'))

@main_blueprint.route('/users')
@roles_accepted('admin')
def user_admin_page():
    users = User.query.all()
    return render_template('pages/admin/users.html', users=users)

@main_blueprint.route('/create_user', methods=['GET', 'POST'])
@roles_accepted('admin')
def create_user_page():
    if current_app.config.get('USER_LDAP', False):
        abort(400)

    form = UserProfileForm()
    roles = Role.query.all()
    form.roles.choices = [(x.id,x.name) for x in roles]

    if form.validate():
        user = User.query.filter(User.email == request.form['email']).first()
        if not user:
            user = User(email=form.email.data,
                        first_name=form.first_name.data,
                        last_name=form.last_name.data,
                        password=current_app.user_manager.hash_password(form.password.data),
                        active=True,
                        email_confirmed_at=datetime.datetime.utcnow())
            db.session.add(user)
            db.session.commit()
            allowed_roles = form.roles.data
            for role in roles:
                if role.id not in allowed_roles:
                    if role in user.roles:
                        user.roles.remove(role)
                else:
                    if role not in user.roles:
                        user.roles.append(role)
            db.session.commit()
            flash('You successfully created the new user.', 'success')
            return redirect(url_for('main.user_admin_page'))
        flash('A user with that email address already exists', 'error')
    return render_template('pages/admin/create_user.html', form=form)


@main_blueprint.route('/users/<user_id>/delete', methods=['GET', 'POST'])
@roles_accepted('admin')
def delete_user_page(user_id):
    if current_app.config.get('USER_LDAP', False):
        abort(400)
    form = ConfirmationForm()
    user = User.query.filter(User.id == user_id).first()
    if not user:
        abort(404)
    if form.validate():
        db.session.query(UsersRoles).filter_by(user_id = user_id).delete()
        db.session.query(User).filter_by(id = user_id).delete()
        db.session.commit()
        flash('You successfully deleted your user!', 'success')
        return redirect(url_for('main.user_admin_page'))
    return render_template('pages/admin/delete_user.html', form=form)


@main_blueprint.route('/users/<user_id>/edit', methods=['GET', 'POST'])
@roles_accepted('admin')
def edit_user_page(user_id):
    if current_app.config.get('USER_LDAP', False):
        abort(400)

    user = User.query.filter(User.id == user_id).first()
    if not user:
        abort(404)

    form = UserProfileForm(obj=user)
    roles = Role.query.all()
    form.roles.choices = [(x.id,x.name) for x in roles]

    if form.validate():
        if 'password' in request.form and len(request.form['password']) >= 8:
            user.password = current_app.user_manager.hash_password(request.form['password'])
        user.email = form.email.data
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.active = form.active.data

        allowed_roles = form.roles.data
        for role in roles:
            if role.id not in allowed_roles:
                if role in user.roles:
                    user.roles.remove(role)
            else:
                if role not in user.roles:
                    user.roles.append(role)

        db.session.commit()
        flash('You successfully edited the user.', 'success')
        return redirect(url_for('main.user_admin_page'))

    form.roles.data = [role.id for role in user.roles]
    return render_template('pages/admin/edit_user.html', form=form)

@main_blueprint.route('/pages/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    if current_app.config.get('USER_LDAP', False):
        abort(400)

    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('main.user_profile_page'))

    # Process GET or invalid POST
    return render_template('pages/user_profile_page.html',
                           current_user=current_user,
                           form=form)

app/templates/pages/admin/create_user.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{{ url_for('main.user_admin_page') }}">Manage Users</a>
</li>
<li class="breadcrumb-item active">
  <a href="{{ url_for('main.create_user_page') }}">Create User</a>
</li>
{% endblock %}
{% block content %}

{% from "common/form_macros.html" import render_field, render_checkbox_field, render_multicheckbox_field %}
  <div class="container-fluid">
    <div class="animated fadeIn">
      <div class="card ">
        <form action="" method="POST" class="form" role="form">
          <div class="card-header ">
            <strong>Create User</strong>
          </div>
          <div class="card-body ">
                {{ form.hidden_tag() }}
                {{ render_field(form.first_name) }}
                {{ render_field(form.last_name) }}
                {{ render_field(form.email) }}
                {{ render_field(form.password) }}
                {{ render_checkbox_field(form.active) }}
                {{ render_multicheckbox_field(form.roles) }}
          </div>
          <div class="card-footer ">
            <button type="submit " class="btn btn-sm btn-primary "><i class="fa fa-dot-circle-o "></i> Submit</button>
          </div>
        </form>
      </div>
</div>
{% endblock %}

app/templates/pages/admin/delete_user.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{{ url_for('main.user_admin_page') }}">Manage Users</a>
</li>
<li class="breadcrumb-item active">
  <a href="{{ url_for('main.create_user_page') }}">Create User</a>
</li>
{% endblock %}
{% block content %}

{% from "common/form_macros.html" import render_field, render_submit_field %}
  <div class="container-fluid">
    <div class="animated fadeIn">
      <div class="card ">
        <form action="" method="POST" class="form" role="form">
          <div class="card-header ">
            <strong>Delete User</strong>
          </div>
          <div class="card-body ">
            {{ form.hidden_tag() }}
            Are you sure you want to delete this user?
          </div>
          <div class="card-footer ">
            <button type="submit " class="btn btn-sm btn-primary "><i class="fa fa-dot-circle-o "></i> Submit</button>
          </div>
        </form>
      </div>
</div>
{% endblock %}

app/templates/pages/admin/edit_user.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{{ url_for('main.user_admin_page') }}">Manage Users</a>
</li>
{% endblock %}
{% block content %}

{% from "common/form_macros.html" import render_field, render_checkbox_field, render_multicheckbox_field %}
  <div class="container-fluid">
    <div class="animated fadeIn">
      <div class="card ">
        <form action="" method="POST" class="form" role="form">
          <div class="card-header ">
            <strong>Edit User</strong>
          </div>
          <div class="card-body ">
                {{ form.hidden_tag() }}
                {{ render_field(form.first_name) }}
                {{ render_field(form.last_name) }}
                {{ render_field(form.email) }}
                {{ render_field(form.password) }}
                {{ render_checkbox_field(form.active) }}
                {{ render_multicheckbox_field(form.roles) }}
          </div>
          <div class="card-footer ">
            <button type="submit " class="btn btn-sm btn-primary "><i class="fa fa-dot-circle-o "></i> Submit</button>
          </div>
        </form>
      </div>
</div>
{% endblock %}

app/templates/pages/admin/users.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
{% block breadcrumb %}
<li class="breadcrumb-item active">
  <a href="{{ url_for('main.user_admin_page') }}">Manage Users</a>
</li>
{% endblock %}
{% block content %}
<div class="card ">
    <div class="card-header ">
      <strong>Users</strong>
      <a href={{ url_for('main.create_user_page') }} class="btn btn-pill btn-sm btn-primary pull-right">Create User</a>
    </div>
    <div class="card-body ">
      <table class="table table-hover table-striped" style="padding-top: 50px;">
        <thead>
          <tr>
            <th>Email</th>
            <th>Username</th>
            <th>Name</th>
            <th>Role</th>
            <th>Confirmed</th>
            {% if not config.get('USER_LDAP', False) %}
            <th>Actions</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
          <tr>
            <td>{{user.email}}</td>
            <td>{{user.username}}</td>
            <td>{{user.name()}}</td>
            <td>{% for role in user.roles %}{{ role.name }}{{ ", " if not loop.last }}{% endfor %}</td>
            <td>{{user.email_confirmed_at}}</td>
            {% if not config.get('USER_LDAP', False) %}
            <td>
              <div class="btn-group" role="group" aria-label="...">
                <a href="{{ url_for('main.edit_user_page', user_id=user.id) }}"><i class="fa fa-pencil"></i></a>
              </div>
              <div class="btn-group" role="group" aria-label="...">
                <a href="{{ url_for('main.delete_user_page', user_id=user.id) }}"><i class="fa fa-remove"></i></a>
              </div>
            </td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="card-footer ">
    </div>
</div>
{% endblock %}