app/views/misc_views.py
# Copyright 2017 Twin Tech Labs. All rights reserved

from flask import Blueprint, redirect, render_template, current_app, abort
from flask import request, url_for, flash, send_from_directory, jsonify, render_template_string
from flask_user import current_user, login_required, roles_accepted

from app import db
from app.models.user_models import UserProfileForm, User, UsersRoles, Role
from app.utils.forms import ConfirmationForm
import uuid, json, os
import datetime

# When using a Flask app factory we must use a blueprint to avoid needing 'app' for '@app.route'
main_blueprint = Blueprint('main', __name__, template_folder='templates')

# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route('/')
def member_page():
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    return render_template('pages/member_base.html')

# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route('/admin')
@roles_accepted('admin')
def admin_page():
    return redirect(url_for('main.user_admin_page'))

@main_blueprint.route('/users')
@roles_accepted('admin')
def user_admin_page():
    users = User.query.all()
    return render_template('pages/admin/users.html', users=users)

@main_blueprint.route('/create_user', methods=['GET', 'POST'])
@roles_accepted('admin')
def create_user_page():
    if current_app.config.get('USER_LDAP', False):
        abort(400)

    form = UserProfileForm()
    roles = Role.query.all()
    form.roles.choices = [(x.id,x.name) for x in roles]

    if form.validate():
        user = User.query.filter(User.email == request.form['email']).first()
        if not user:
            user = User(email=form.email.data,
                        first_name=form.first_name.data,
                        last_name=form.last_name.data,
                        password=current_app.user_manager.hash_password(form.password.data),
                        active=True,
                        email_confirmed_at=datetime.datetime.utcnow())
            db.session.add(user)
            db.session.commit()
            allowed_roles = form.roles.data
            for role in roles:
                if role.id not in allowed_roles:
                    if role in user.roles:
                        user.roles.remove(role)
                else:
                    if role not in user.roles:
                        user.roles.append(role)
            db.session.commit()
            flash('You successfully created the new user.', 'success')
            return redirect(url_for('main.user_admin_page'))
        flash('A user with that email address already exists', 'error')
    return render_template('pages/admin/create_user.html', form=form)


@main_blueprint.route('/users/<user_id>/delete', methods=['GET', 'POST'])
@roles_accepted('admin')
def delete_user_page(user_id):
    if current_app.config.get('USER_LDAP', False):
        abort(400)
    form = ConfirmationForm()
    user = User.query.filter(User.id == user_id).first()
    if not user:
        abort(404)
    if form.validate():
        db.session.query(UsersRoles).filter_by(user_id = user_id).delete()
        db.session.query(User).filter_by(id = user_id).delete()
        db.session.commit()
        flash('You successfully deleted your user!', 'success')
        return redirect(url_for('main.user_admin_page'))
    return render_template('pages/admin/delete_user.html', form=form)


@main_blueprint.route('/users/<user_id>/edit', methods=['GET', 'POST'])
@roles_accepted('admin')
def edit_user_page(user_id):
    if current_app.config.get('USER_LDAP', False):
        abort(400)

    user = User.query.filter(User.id == user_id).first()
    if not user:
        abort(404)

    form = UserProfileForm(obj=user)
    roles = Role.query.all()
    form.roles.choices = [(x.id,x.name) for x in roles]

    if form.validate():
        if 'password' in request.form and len(request.form['password']) >= 8:
            user.password = current_app.user_manager.hash_password(request.form['password'])
        user.email = form.email.data
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.active = form.active.data

        allowed_roles = form.roles.data
        for role in roles:
            if role.id not in allowed_roles:
                if role in user.roles:
                    user.roles.remove(role)
            else:
                if role not in user.roles:
                    user.roles.append(role)

        db.session.commit()
        flash('You successfully edited the user.', 'success')
        return redirect(url_for('main.user_admin_page'))

    form.roles.data = [role.id for role in user.roles]
    return render_template('pages/admin/edit_user.html', form=form)

@main_blueprint.route('/pages/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    if current_app.config.get('USER_LDAP', False):
        abort(400)

    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('main.user_profile_page'))

    # Process GET or invalid POST
    return render_template('pages/user_profile_page.html',
                           current_user=current_user,
                           form=form)

app/templates/dark_layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title_tag %}
        <title>{{ config['APP_NAME'] }}{% block title %}{% endblock %}</title>
        {% endblock %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Place favicon.ico and apple-touch-icon(s) in the root directory -->
        <link rel="shortcut icon" href="images/favicon.ico">

        <!-- stylesheets -->
        <!-- stylesheets and javascript -->
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css" integrity="sha256-q5+FXlQok94jx7fkiX65EGbJ27/qobH6c6gmhngztLE=" crossorigin="anonymous" />

        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" integrity="sha384-rgWRqC0OFPisxlUvl332tiM/qmaNxnlY46eksSZD84t+s2vZlqGeHrncwIRX7CGp" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.js" integrity="sha256-nB5IzxtznpdsVh/iELG3YdRF71rcxuh4tItH2jWfg/w=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.4.0/css/perfect-scrollbar.css" integrity="sha256-e2UIyejgTejr/sXeLOHEMDvEagonkoPv9+JIwckAqRs=" crossorigin="anonymous" />

        <link href="{{ url_for('static', filename='/coreui/dist/css/coreui.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='/coreui/dist/js/coreui.min.js') }}"></script>

    </head>
    <body>
        {% block body %}
        <div class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
          <header class="app-header navbar">
            <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.member_page') }}">
              {{ config['APP_NAME'] }}
            </a>
            <a class="nav-link nav-link--rounded pull-right" style="margin-right: 10px;" href="{{ url_for('user.logout') }}">
              Sign out
            </a>
          </header>
          <div class="app-body">
            <div class="sidebar">
              <nav class="sidebar-nav">
                <ul class="nav">

                  <li class="nav-item nav-dropdown">
                    <a class="nav-link nav-dropdown-toggle" href="#">
                      <i class="nav-icon icon-bell"></i> My Account</a>
                    <ul class="nav-dropdown-items">
                      {% if not config.get('USER_LDAP', False) %}
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.user_profile_page') }}">
                          <i class="nav-icon icon-drop"></i> Profile</a>
                      </li>

                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.change_password') }}">
                          <i class="nav-icon icon-drop"></i> Password</a>
                      </li>
                      {% endif %}

	              {% if current_user.is_authenticated %}
			{% if current_user.has_role('admin') or current_user.has_role('dev') %}
		          <li class="nav-item">
			    <a class="nav-link" href="{{ url_for('apikeys.apikeys_index') }}">
			      <i class="nav-icon icon-drop"></i> API Keys</a>
		          </li>
			{% endif %}
                      {% endif %}

                    </ul>
                  </li>

	          {% if current_user.is_authenticated %}
			  {% if current_user.has_role('admin') %}
			  <li class="nav-title">Administration</li>
			  <li class="nav-item">
			    <a class="nav-link" href="{{ url_for('main.user_admin_page') }}">
			      <i class="nav-icon icon-drop"></i> Manage Users</a>
			  </li>
			  {% endif %}
                  {% endif %}

                </ul>
              </nav>
            </div>

          {% block pre_content %}{% endblock %}

          <main class="main">
          {# One-time system messages called Flash messages #}
          {% block flash_messages %}
              {%- with messages = get_flashed_messages(with_categories=true) -%}
                  {% if messages %}
                      {% for category, message in messages %}
                          {% if category=='error' %}
                              {% set category='danger' %}
                          {% endif %}
                          <div style="margin-bottom: -2px;" role="alert" class="alert alert-{{category}} alert-dismissible fade show">{{ message|safe }}</div>
                      {% endfor %}
                  {% endif %}
              {%- endwith %}
          {% endblock %}

          <!-- Breadcrumb-->
          <ol class="breadcrumb">
            {% block breadcrumb %}
            {% endblock %}
          </ol>

          <div class="container-fluid">
            <div class="animated fadeIn">
              {% block content %}{% endblock %}
            </div>
          </div>

          </main>
          {% block post_content %}{% endblock %}

        {% endblock %}
        </div>
        <footer class="app-footer">
          <div>{{ config['APP_NAME'] }} &copy; {{ now().year }} {{ config['APP_OWNER_NAME'] }}</div>
        </footer>
      </div>
        <script>
            // Hide loader
            (function() {
                $(".alert").fadeTo(4000, 500).slideUp(500, function(){
                    $(".alert").slideUp(500);
                });
                {% block onstart_javascript %}{% endblock %}
            })();
            {% block page_load_javascript %}{% endblock %}
        </script>
    </body>
</html>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title_tag %}
        <title>{{ config['APP_NAME'] }}{% block title %}{% endblock %}</title>
        {% endblock %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Place favicon.ico and apple-touch-icon(s) in the root directory -->
        <link rel="shortcut icon" href="images/favicon.ico">

        <!-- stylesheets -->
        <link href="{{ url_for('static', filename='css/flag-icon-css/css/flag-icon.min.css') }}" rel="stylesheet">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css" integrity="sha256-q5+FXlQok94jx7fkiX65EGbJ27/qobH6c6gmhngztLE=" crossorigin="anonymous" />

        <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">


        <link href="{{ url_for('static', filename='/coreui/dist/css/coreui.css') }}" rel="stylesheet">

        <!-- javascript -->
        <!--
        <script src="{{ url_for('static', filename='js/popper.js/dist/umd/popper.min.js') }}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
        -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


        <script src="{{ url_for('static', filename='js/pace-progress/pace.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/perfect-scrollbar/dist/perfect-scrollbar.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/@coreui/coreui/dist/js/coreui.min.js') }}"></script>

    </head>
    <body>
        {% block body %}

        <div id="main-div" class="with-margins">
        {% block pre_content %}{% endblock %}

        {% block content %}{% endblock %}

        {% block post_content %}{% endblock %}
        </div>

        {% endblock %}

        <script>
            // Hide loader
            (function() {
                $(".alert").fadeTo(4000, 500).slideUp(500, function(){
                    $(".alert").slideUp(500);
                });
            })();
        </script>
    </body>
</html>